const NEGATIVENUMBERERRORTEXT = "Number should not be negative";
const NUMBEROUTOFBOUNDERRORTEXT = "Number should be be in [1,2147483647]";
const SENDINGMESSAGEERRORTEXT = "Error sending message to Kafka ";
const CONNECTINGTOKAFKAERRORTEXT= "Error connecting to Kafka ";
const FETCHINGTABLESERRORTEXT = "Error fetching tables ";
const EXECUTINGQUERYERRORTEXT = "Error executing query for table ";
const CONNECTINGTOMYSQLERRORTEXT = "Error connecting to MySQL ";
const CREATINGDATABASEERRORTEXT = "Error creating database ";
const FETCHINGDATAFROMTABLEERRORTEXT = "Error fetching data from table";
const FAILEDFETCHINGTABLESERRORTEXT = "Failed to fetch tables";
const INVALIDTABLENAMETEXT = "Invalid table name";
const CONNECTIONCREATEDSUCCESSFULLYTEXT = "Connection created successfully.";
const NEGATIVENUMBERERRORCODE = "DMA008";
const NUMBEROUTOFBOUNDERRORCODE = "DMA009";
const INVALIDTABLENAMECODE = "DMA027";
module.exports = {
    FETCHINGTABLESERRORTEXT,
    EXECUTINGQUERYERRORTEXT,
    CONNECTINGTOMYSQLERRORTEXT,
    CREATINGDATABASEERRORTEXT,
    NEGATIVENUMBERERRORTEXT, 
    NUMBEROUTOFBOUNDERRORTEXT,
    SENDINGMESSAGEERRORTEXT,
    CONNECTIONCREATEDSUCCESSFULLYTEXT,
    CONNECTINGTOKAFKAERRORTEXT,
    FETCHINGDATAFROMTABLEERRORTEXT,
    FAILEDFETCHINGTABLESERRORTEXT,
    INVALIDTABLENAMETEXT,
    NEGATIVENUMBERERRORCODE,
    NUMBEROUTOFBOUNDERRORCODE,
    INVALIDTABLENAMECODE
}