apiVersion: v1
kind: Service
metadata:
  name: main-app-service
  labels:
    app: main-app
spec:
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 100
      targetPort: 3001
  type: LoadBalancer