apiVersion: v1
kind: Service
metadata:
  name: mongo-connector-{{ .Values.INSTANCE_ID }}-service
spec:
  type:  LoadBalancer
  selector:
    app: mongo-connector-{{ .Values.INSTANCE_ID }}
  ports:
    - protocol: TCP
      port: {{ .Values.SERVICE_PORT }}
      targetPort: 3002