apiVersion: v1
kind: Service
metadata:
  name: mysql-connector-{{ .Values.INSTANCE_ID }}-frontend-service
spec:
  selector:
    app: mysql-connector-{{ .Values.INSTANCE_ID }}-frontend
  ports:
    - protocol: TCP
      port: {{.Values.SERVICE_PORT_FRONT}}
      targetPort: {{.Values.SERVICE_PORT_FRONT}}
  type: LoadBalancer